'use client'

import { Inter } from "next/font/google";
import SideNavbar from "./component/Nav";
import "./globals.css";
// If you are using Less, import the `index.less` file.
import 'rsuite/dist/rsuite.min.css';
import TopNav from "./component/TopNav";
import React from "react";
const inter = Inter({ subsets: ["latin"] });

 const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [expanded, setExpanded] = React.useState(true);
const handelEcpand=()=>{
  console.log("clicked",expanded);
  setExpanded(!expanded)
}
  return (

    <html lang="en">
    
      <body >
      <TopNav handelEcpand={handelEcpand}></TopNav>
        
        <div className="app">
        <SideNavbar expanded={expanded}/>
        {children}
        </div>
      
        </body>
    </html>
  );
}
